USE [master]
GO

/****** Object:  Database [CadCS]    Script Date: 10/9/2019 12:06:44 AM ******/
CREATE DATABASE [CadCS]
GO

ALTER DATABASE [CadCS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CadCS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CadCS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CadCS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CadCS] SET ARITHABORT OFF 
GO

ALTER DATABASE [CadCS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CadCS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CadCS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CadCS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CadCS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CadCS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CadCS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CadCS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CadCS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CadCS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CadCS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CadCS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CadCS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CadCS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CadCS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CadCS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CadCS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CadCS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CadCS] SET  MULTI_USER 
GO

ALTER DATABASE [CadCS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CadCS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CadCS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CadCS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CadCS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CadCS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CadCS] SET  READ_WRITE 
GO


USE [CadCS]
IF EXISTS(SELECT * FROM SYS.SYSUSERS WHERE NAME = 'UNX')
	DROP USER UNX
IF EXISTS(SELECT * FROM SYS.SYSLOGINS WHERE NAME = 'UNX')
	DROP LOGIN UNX
CREATE LOGIN UNX WITH PASSWORD = '1234'
CREATE USER UNX FROM LOGIN UNX
GRANT CREATE TABLE ON DATABASE :: CadCS TO UNX
GRANT SELECT ON SCHEMA :: dbo TO UNX
GRANT INSERT ON SCHEMA :: dbo TO UNX
GRANT DELETE ON SCHEMA :: dbo TO UNX
GRANT UPDATE ON SCHEMA :: dbo TO UNX
EXEC SP_ADDROLEMEMBER db_backupoperator, UNX
EXEC SP_ADDROLEMEMBER db_OWNER, UNX

USE [CadCS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[clientes]    Script Date: 10/9/2019 12:15:22 AM ******/
CREATE TABLE [dbo].[clientes](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](50) NULL,
	[rua] [varchar](50) NULL,
	[num] [varchar](10) NULL,
	[cep] [varchar](10) NULL,
	[estado] [varchar](50) NULL,
	[cidade] [varchar](50) NULL,
	[bairro] [varchar](50) NULL,
	[fone] [varchar](14) NULL,
	[cpf] [varchar](18) NULL,
	[email] [varchar](50) NULL,
 CONSTRAINT [PK_ID] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[contas]    Script Date: 10/9/2019 12:15:30 AM ******/
CREATE TABLE [dbo].[contas](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[descricao] [varchar](50) NOT NULL,
	[agencia] [varchar](10) NOT NULL,
	[numero] [varchar](20) NOT NULL,
 CONSTRAINT [PK_contas] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[produtos]    Script Date: 10/9/2019 12:18:21 AM ******/
CREATE TABLE [dbo].[produtos](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[descricao] [varchar](50) NOT NULL,
	[unidade] [varchar](10) NULL,
	[preco] [numeric](10, 2) NULL,
 CONSTRAINT [PK_produtos] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[vendas]    Script Date: 10/9/2019 5:50:47 PM ******/
CREATE TABLE [dbo].[vendas](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[id_clientes] [int] NULL,
	[nome_clientes] [varchar](50) NULL,
	[dataven] [datetime] NULL,
	[totalven] [numeric](10, 2) NULL,
 CONSTRAINT [PK_vendas] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[vendas]  WITH CHECK ADD  CONSTRAINT [FK_vendas_clientes] FOREIGN KEY([id_clientes])
REFERENCES [dbo].[clientes] ([id])
GO

ALTER TABLE [dbo].[vendas] CHECK CONSTRAINT [FK_vendas_clientes]
GO

/****** Object:  Table [dbo].[proven]    Script Date: 10/9/2019 5:51:20 PM ******/
CREATE TABLE [dbo].[proven](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[id_vendas] [int] NULL,
	[id_produtos] [int] NULL,
	[descricao_produtos] [varchar](50) NULL,
	[preco] [numeric](10, 2) NULL,
	[qtde] [numeric](10, 2) NULL,
	[total_item] [numeric](10, 2) NULL,
 CONSTRAINT [PK_proven] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
